apiVersion: batch/v1
kind: Job
metadata:
  name: my-script-job1
spec:
  template:
    spec:
      containers:
      - name: hello-world-container #my-script-container
        image: ghcr.io/nova-ch/dp:v0.0  # Replace with your actual image
        command: ["ls", "/app"]
        command: ["python"]  #["/bin/sh", "-c"]
        args: ["testDB.py"]  #["./my-script.sh"]  # Replace with your actual script
      restartPolicy: OnFailure  # This ensures that the job will restart if the script fails

