name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust the branch as necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.G_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dp:v0.0
          # Optionally add more tags if needed, e.g. :v1.0

    - name: Test Docker image
      run: |
        docker run --rm ghcr.io/${{ github.repository_owner }}/dp:v0.0 python test.py

